require:
  - rubocop-rspec
  - rubocop-rspec_rails

plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'bin/**'
    - 'vendor/**'
    - 'node_modules/**'
    - 'tmp/**'
    - 'log/**'
    - 'coverage/**'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/application.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 8

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

